resources/views/cart/partials/sidebar/summary.blade.php
also moved it to be above tax so that it makes sense
=> Change shipping to be shown excluding tax for parity with checkout summary

composer.json, resources/views/cart/coupon.blade.php, resources/views/checkout/partials/address-cards-popup.blade.php
In https://github.com/rapidez/core/pull/304, I updated Heroicons to version 2. In the update, some icons have changed, so this should also be updated in the rapidez/checkout-theme package.
=> Heroicons v2 compatibility

resources/js/package.js
There might be a cleaner way to do this? The need for this update shows me that we really need to fix the hide_billing variable instead of working around it like this.
This is necessary, by the way, because the rapidez checkout assumes when hide_billing is true that billingAddress is equal to shippingAddress, even when this might not be the case.
=> Update hide_billing to be set correctly

resources/js/components/AddressCard.vue, resources/js/components/CheckoutSuccessAddresses.vue, resources/js/package.js, resources/views/checkout/partials/sections/success/order-info.blade.php, resources/views/components/address.blade.php, resources/views/components/card/address.blade.php
Address card:
- Allow custom titles
- Allow street to be a string (e.g. as retrieved from the `sales_order_address` table)
Checkout success:
- Grab addresses from order instead of from checkout component
- If there is more than 1 shipping addresses, assume the first one is a pickup location
- Format appropriately, clean up template with loop
=> Checkout success fixes

resources/views/components/address-form.blade.php
So it doesn't clash with itself when you separate out the shipping and billing addresses.
=> Checkbox for business separated by type

resources/views/account/partials/orders.blade.php, resources/views/components/dashboard/item/index.blade.php, resources/views/components/input/label.blade.php
Icon width is necessary so that it doesn't cause inconsistent widths when the icons themselves aren't square. Heroicons are all square, but not all `x-icon` icons have to be :)
=> Fix text-inactive missing -ct-, add icon width

resources/views/components/button/index.blade.php
This is relevant if you're changing the tag to something like a label.
=> Add cursor-pointer to base button

resources/views/cart/cart.blade.php, resources/views/cart/partials/bottom-bar.blade.php, resources/views/cart/partials/products.blade.php
Removed includes and added them directly into the <x-sections component and <x-toolbar component for consistency. Also removed the margin on the table, since the <x-sections provides for spacing.
=> Removed margin and added components in the cart

resources/views/checkout/partials/sections/payment.blade.php, resources/views/checkout/partials/sections/payment/agreement-checkbox.blade.php, resources/views/checkout/partials/sections/payment/payment-methods.blade.php, resources/views/checkout/partials/sections/success/create-account-title.blade.php, resources/views/checkout/partials/sections/success/create-account.blade.php, resources/views/checkout/partials/sections/success/logged-in.blade.php
If we have to change something in payment.blade for example the payment methods we had to override the entire file. I moved some items to there own files to make override easier for small parts in the payment and success page step.
=> Split up to more blade files to make override easier

resources/views/account/partials/layout.blade.php
This is relevant for, for example, multiple wishlists, where you can't really use the title section.
=> Only show title in account center if it exists

resources/views/checkout/partials/address-cards.blade.php, resources/views/components/address.blade.php, resources/views/components/card/address.blade.php
If a logged in customer only had a default billing or default shipping address the other field would not get filled and render blank.
There would be no validation to point that flaw out to the customer either.
This PR replaces the blank area with a button to select an address from your addresses with a dummy input to ensure the address should not be empty during the checkout process
=> Show a button to select address + frontend validation if default address is missing

resources/views/cart/partials/product/description.blade.php, resources/views/cart/partials/product/image.blade.php, resources/views/cart/partials/product/price.blade.php, resources/views/cart/partials/product/remove-button.blade.php, resources/views/cart/partials/products.blade.php, resources/views/checkout/partials/sections/newsletter.blade.php, resources/views/checkout/steps/credentials.blade.php
Splitting up the cart items like this allows for more easily overwriting only the stuff that is necessary, say you want to slightly change the styling of the item description in your implementation.
=> Add newsletter to checkout & splice up cart products listing into separate parts

resources/views/checkout/partials/layout.blade.php
The checkout as it stands does not work in Rapidez 2 and you get a blank page. Rapidez 2 does not have the `cart` component anymore and thus doesn't use this `hasItems` variable.
=> [2.x] Rapidez v2 compatibility

resources/views/components/newsletter/index.blade.php, resources/views/components/newsletter/partials/checkbox.blade.php
The way this work(ed) was if you check the checkbox on the registration form, it would send the graphql request right away instead of subscribing the customer in the register(createCustomer) request so it's linked. Now it does go in one request.
=> Fix the newsletter subscribe to not mutate right away

resources/views/checkout/partials/sections/payment.blade.php, resources/views/checkout/steps/payment.blade.php
Adding anything into this card required overwriting a file with a bunch of functionality unnecessarily. By moving the card outside of the include we can limit the need for that, keeping it to a simpler file to overwrite.
=> [2.x] Move card outside of include to reduce need for overwrites

resources/views/account/order.blade.php
This currently gives problems with viewing the order when changes have been made. For example order status progression is not directly visible without clearing the localeStorage.
=> disable graphql cache of order view

resources/views/components/newsletter/partials/checkbox.blade.php
This expression was empty when the value was false, causing the whole checkout to break.
=> [2.x] Fix empty expression error

resources/views/account/partials/sections/edit/newsletter.blade.php, resources/views/components/newsletter/index.blade.php
`data` is undefined when it's not wrapped in a component that has `data` available and there doesn't seem to be a good way to check for undefined-ness in this particular context. This then consequently throws an error and breaks the whole checkout success.
=> Fix newsletter in checkout success for logged in customers

resources/views/components/newsletter/partials/checkbox.blade.php
This ended up giving a 500 error on the account register page and possibly others. We can just assume it's false when not defined.
=> [2.x] Add default to isPartOfAnotherForm prop

resources/core-overwrites/account/partials/layout.blade.php
Some packages that add to the account center (like `rapidez/multiple-wishlists`) will try to use the default core layout, causing them to have the wrong layout.
=> [2.x] Override account layout partial

resources/views/account/edit.blade.php, resources/views/account/partials/sections/edit/email.blade.php, resources/views/account/partials/sections/edit/password.blade.php
This has seemingly just been wrong for quite a while. I noticed this a few weeks ago but figured it was surely project-specific so I had made a story there.
The `change password` box was actually just a `change email` mutation, and there was no change password mutation at all. I'm surprised this hadn't already been noticed anywhere else 🙃 
(this works fine in the core, so I'm not sure how this came to be)
=> [2.x] Change password that actually works

resources/views/account/partials/address-cards-popup.blade.php, resources/views/checkout/partials/address-card.blade.php, resources/views/checkout/partials/address-cards-popup.blade.php, resources/views/components/popup.blade.php
A few small fixes for the address popup see my screenshot below.
**When there are to much addresses in the popup it show like this:**
_This is fixed for desktop & mobile:_
**From 640px the view will be like this:**
_It will be shown from 1024px now (breakpoint lg)_
=> Fix address popup when list is to long | Fix text alignment

resources/views/checkout/partials/sections/login/logged-out.blade.php
The core [has this link in there already](https://github.com/rapidez/core/blob/2.x/resources/views/checkout/steps/login.blade.php#L31), but it was missing here. This is now fixed.
=> Add "forgot password" link to checkout login section

lang/nl.json, resources/views/cart/partials/product/description.blade.php, resources/views/cart/partials/sidebar/summary.blade.php
Also see depending on:
https://github.com/rapidez/core/pull/627
https://github.com/rapidez/core/pull/628 
Internally there's a story to have some extra frontend added for this.
V2: #127
=> [3.x] Disable checkout button and add notice if not in stock

resources/views/account/partials/address-cards.blade.php, resources/views/account/partials/register-account.blade.php, resources/views/cart/partials/product/image.blade.php, resources/views/checkout/pages/credentials.blade.php, resources/views/checkout/partials/address-card.blade.php, resources/views/checkout/partials/address-cards.blade.php, resources/views/checkout/partials/buttons/address.blade.php, resources/views/checkout/partials/buttons/new-address.blade.php, resources/views/checkout/partials/sections/login.blade.php, resources/views/checkout/partials/sections/login/logged-out.blade.php, resources/views/checkout/partials/sidebar/summary.blade.php, resources/views/components/address-form.blade.php, resources/views/components/card/index.blade.php, resources/views/components/input/checkbox.blade.php, resources/views/components/input/password.blade.php, resources/views/components/layout/index.blade.php, resources/views/components/layout/sidebar.blade.php, resources/views/components/layout/two-column.blade.php, resources/views/components/title/base.blade.php
- Changed breakpoints see also: #124 
- (Small) frontend fixes after changes for V3
=> [3.x] Changed breakpoints | Frontend fixes checkout

resources/views/checkout/partials/sections/login/logged-out.blade.php
see: https://github.com/rapidez/core/pull/613
=> [2.x] Require an actual login

resources/views/components/newsletter/partials/checkbox.blade.php
Previously this was only set to `variables.is_subscribed`, however this doesn't always exist or doesn't always represent the actual value we're looking for.
This went wrong with the newsletter in the checkout when logged in (but only in 2.x), as in that scenario it just uses `checkout.newsletter_subscribe` instead of a gql query.
=> [2.x] Use v-model variable for is_subscribed setter

resources/views/components/newsletter/partials/checkbox.blade.php
See #136
It's not necessarily a direct issue in 3.x because the checkout works differently here, but the issue with the component itself is still the same.
=> [3.x] Use v-model variable for is_subscribed setter

resources/views/checkout/partials/sections/login/logged-out.blade.php
See https://github.com/rapidez/core/pull/639
=> [3.x] Remove password check

resources/views/components/button/base.blade.php, resources/views/components/button/link.blade.php, resources/views/components/dashboard/item/index.blade.php, resources/views/components/dashboard/sidebar-item/index.blade.php, resources/views/components/separated-listing/index.blade.php
As this component is now integrated into `rapidez/blade-components`, an update that also comes with rapidez v3, its signature has been changed to `x-rapidez::tag`.
=> [3.x] Use x-rapidez::tag

resources/views/cart/overview.blade.php, resources/views/checkout/partials/sections/payment.blade.php, resources/views/components/button/base.blade.php, resources/views/components/card/address.blade.php
- The query was missed in the upgrade to 3.x
- The button has one use case in confira where it becomes a label. Took the same code from the core
- The payment step needs a gap between payment methods
=> [3.x] Fix getCart query & styling for payment step & button label

resources/views/components/input/country-select.blade.php
The loop wasn't working correct this will fix the vue warning "infinite loop"
Also see this pull request: https://github.com/rapidez/core/pull/730
=> Fix country select loop

resources/views/components/address-form.blade.php
The correct default here is `'opt'` and not `0`. This was already correct in the core.
=> [3.x] Update default on company_show

composer.json
Confira requires version 3.5.0 for the change here:https://github.com/rapidez/confira/pull/35.
=> Make use of core version 3.5

resources/views/checkout/partials/sections/login/logged-out.blade.php
Relates to https://github.com/rapidez/core/pull/950. Doesn't break backwards compatibility.
=> [4.x] Make login required an optional thing

resources/views/checkout/partials/sections/payment/payment-methods.blade.php
=> Prevent cutting icons from the side

resources/views/account/partials/resetpassword.blade.php
Hide the `Security token` field in the form. 
Redirect to the login page when the user succesfully resetted the password.
=> Improve resetpassword flow
