composer.json, resources/views/cart/coupon.blade.php, resources/views/checkout/partials/address-cards-popup.blade.php
Reverts rapidez/checkout-theme#16 as it mismatches, when https://github.com/rapidez/core/pull/307 is merged we need to revert this revert 🙃
=> Revert "Heroicons v2 compatibility"

config/rapidez-checkout-theme.php, resources/views/checkout/steps/success.blade.php
=> Add condition in config for creating account in checkout success

resources/views/cart/partials/products.blade.php
=> specialPrice doesn't exist in the cart

resources/views/account/partials/register-account.blade.php
=> Use correct config function

resources/views/components/progress-bar/index.blade.php
This should keep backwards compatibility this way as well.
https://github.com/rapidez/core/pull/356
=> Update config usages for new config

composer.json, resources/views/cart/coupon.blade.php, resources/views/checkout/partials/address-cards-popup.blade.php
Reverts rapidez/checkout-theme#29
=> Heroicons revertception

resources/views/components/button/index.blade.php, resources/views/components/input/password.blade.php
I guess these came in between the reverts. Should all be good now.
=> Update heroicons some more

config/rapidez-checkout-theme.php, resources/views/components/popup.blade.php, resources/views/components/slideover.blade.php
You win some, you lose some. Unfortunately, with the previous "last time I promise" PR for icons, I lost. Turns out I had to fix 3 more old heroicon names that I somehow missed.
=> Actually the real last heroicons v2 fix

resources/views/cart/partials/products.blade.php, resources/views/checkout/partials/sections/payment.blade.php
- Unnecessarily doubled up class confusing tailwind (and myself) causing different behavior on different versions of tailwind
- Don't show checkboxes parent div when there are no checkboxes
=> Small fixes

config/rapidez/checkout-theme.php, resources/views/account/partials/register-account-address.blade.php, resources/views/account/partials/register-account.blade.php
If the option is enabled to show the address form the user will have to enter an address which will automatically be saved as the default shipping & billing
=> Add option to make the user create an address during registration

resources/views/cart/cart.blade.php, resources/views/cart/content.blade.php, resources/views/cart/coupon.blade.php, resources/views/cart/overview.blade.php, resources/views/cart/partials/cart-title.blade.php, resources/views/cart/partials/coupon-field.blade.php, resources/views/cart/partials/products.blade.php, resources/views/components/coupon-field.blade.php, resources/views/components/sections/index.blade.php, resources/views/components/title/index.blade.php
Made it easier to overwrite templates by splitting the frontend into multiple views
=> refactored templates by splitting it into partials

resources/views/account/partials/address-cards-popup.blade.php, resources/views/account/partials/address-cards/buttons.blade.php, resources/views/account/partials/address-cards/delete.blade.php, resources/views/components/button/link.blade.php
Mirror of the 2.x commit but for 1.x
=> Add "delete" button to address cards

resources/views/components/newsletter/partials/checkbox.blade.php
Using braces in blade components gives errors. In this case that's exactly what happened :)
=> Fix attributes error

resources/views/components/newsletter/index.blade.php
=> [1.x] Add :$id to newsletter checkbox

resources/views/components/newsletter/index.blade.php
=> [2.x] Add :$id to newsletter checkbox

resources/views/account/partials/address-cards-popup.blade.php
Missing the `mutating` in the slot scope, and for some reason there was an extra closing tag.
=> [2.x] Fix address cards popup

resources/views/cart/partials/product/remove-button.blade.php
This one was missed in the graphql migration
=> [2.x] Update remove button to 2.x

resources/views/account/address-edit.blade.php, resources/views/account/order.blade.php, resources/views/account/partials/order/order-total.blade.php
I have removed the data from checks for Rapidez v2 compatibility.
In https://github.com/rapidez/account/pull/47/files, the second data has been removed for v2 compatibility, so it also needs to be removed here.
=> Remove data from checks

resources/views/components/newsletter/index.blade.php
This line seemingly accidentally got lost in a previous PR, my bad.
=> [2.x] Re-add isPartOfAnotherForm

resources/views/account/partials/sections/edit/newsletter.blade.php, resources/views/components/newsletter/index.blade.php
Same fix as in 2.x, but for 1.x.
=> [1.x] Fix checkout newsletter for logged in customers

resources/views/account/order.blade.php
This button never had a href so it never worked :) now it does
=> [2.x] Make back button work

resources/views/cart/partials/sidebar/summary.blade.php
These `v-if`s don't work. Fixed here.
=> [2.x] Fix cart summary

resources/views/account/partials/register-account.blade.php
This was only added to the register account address page. Fixed
=> [2.x] Add VAT check in register page

resources/views/cart/partials/product/description.blade.php, resources/views/cart/partials/sidebar/summary.blade.php
Also see depending on:
https://github.com/rapidez/core/pull/627
https://github.com/rapidez/core/pull/628 
Internally there's a story to have some extra frontend added for this.
V3: #128
=> [2.x] Disable checkout button and add notice if not in stock

resources/views/account/partials/address-cards.blade.php, resources/views/account/partials/register-account.blade.php, resources/views/cart/partials/product/image.blade.php, resources/views/checkout/partials/address-cards.blade.php, resources/views/checkout/partials/buttons/address.blade.php, resources/views/checkout/partials/buttons/new-address.blade.php, resources/views/checkout/partials/sidebar/summary.blade.php, resources/views/components/card/index.blade.php, resources/views/components/layout/index.blade.php, resources/views/components/layout/sidebar.blade.php, resources/views/components/layout/two-column.blade.php, resources/views/components/title/base.blade.php
This _could_  be breaking for projects where you use [custom breakpoints ](https://tailwindcss.com/docs/responsive-design#using-custom-breakpoints). 
I changed some breakpoints because on 768px there is not enough space for a sidebar.
=> Changed breakpoints for smaller screens

README.md, resources/core-overwrites/layouts/checkout/footer.blade.php, resources/core-overwrites/layouts/checkout/header.blade.php
same as
https://github.com/rapidez/checkout-theme/pull/138
but for v3
=> Added header and footer

resources/views/account/address-edit.blade.php, resources/views/account/order.blade.php, resources/views/account/partials/order/order-total.blade.php
Follow up on: https://github.com/rapidez/core/pull/604
=> [3.x] Update check props

resources/views/account/address-edit.blade.php, resources/views/account/address-new.blade.php, resources/views/account/partials/address-cards/delete.blade.php
See: https://github.com/rapidez/account/pull/57
=> [3.x] Refresh user data on address change

resources/views/components/input/select.blade.php
2.x version of #150, the 3.x version uses blade-components which works differently and thus is no longer needed.
=> [2.x] Only show label if it has content

resources/views/cart/partials/product/image.blade.php
Depends on https://github.com/rapidez/core/pull/688 to be merged first
=> [3.x] Show variant image in cart

resources/views/components/address-form.blade.php
=> [2.x] Update default on company_show

resources/views/cart/partials/crosssells.blade.php
=> [2.x] Fix crosssells

lang/nl.json
=> [3.x] Remove unnecessary translation

resources/views/account/partials/register-account-address.blade.php, resources/views/account/partials/sections/edit/email.blade.php, resources/views/checkout/partials/address-card.blade.php
=> [4.x] Fix small bugs

resources/views/checkout/partials/sections/success/order-completed-note.blade.php
Align items with flex. Make use of `<strong>` instead of `<span>`
=> Make use of strong tag and make use of flex

.github/workflows/playwright.yml, tests/playwright/checkout.spec.js
See: https://github.com/rapidez/core/pull/1035
=> Playwright Magento version tag
